apiVersion: v1
kind: Secret
metadata:
  name: agent-variables
  labels:
    {{- include "beeai-platform.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.variables }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
