# phoenix.yaml
# https://docs.arize.com/phoenix/self-hosting/deployment-options/kubernetes
{{- if .Values.phoenix.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: phoenix-svc
    {{- include "beeai-platform.labels" . | nindent 4 }}
  name: phoenix-svc
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 6006
      name: frontend
    - port: 8336
      name: backend
      protocol: TCP
      targetPort: 8336
  selector:
    app: phoenix-backend
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: phoenix-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phoenix-backend
      {{- include "beeai-platform.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      # Assume k8s pod service discovery for prometheus
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9090"
        prometheus.io/scrape: "true"
      labels:
        app: phoenix-backend
        {{- include "beeai-platform.labels" . | nindent 8 }}
    spec:
      containers:
        - name: phoenix-backend
          args:
            - -m
            - phoenix.server.main
            - serve
          command:
            - python
          env:
            - name: PHOENIX_GRPC_PORT
              value: "8336"
            - name: PHOENIX_WORKING_DIR
              value: /mnt/data
          # The version of phoenix you want should be used here
          image: {{ .Values.phoenix.image }}
          ports:
            - containerPort: 6006
            - containerPort: 4317
            - containerPort: 9090
          volumeMounts:
            - mountPath: /mnt/data
              name: phoenix-backend
          {{- with .Values.phoenix.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: phoenix-backend
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 8Gi
{{- end }}