apiVersion: v1
kind: Service
metadata:
  name: otel-collector-svc
  labels:
    app: otel-collector
    {{- include "beeai-platform.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8335
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: otel-collector
    {{- include "beeai-platform.selectorLabels" . | nindent 4 }}
