{{- $root := . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: beeai-platform-providers-cm
data:
  registry.yaml: |
    providers:
{{- range $idx, $p := $root.Values.providers }}
      - location: "http://{{ include "agent.fullname" (dict "root" $root "image" $p.location) }}:{{ $root.Values.agent.service.port }}"
{{- end }}
